In [1]:
# from google.colab import files
# uploaded = files.upload()

In [2]:
import os
import glob
import pandas as pd

In [3]:
# Define working directory
os.chdir(r"C:\Users\hguzm\Documents\000. Personal\Bootcamp\Proyectos\FinalProject-Spotify\Original_data")

In [4]:
# Use glob to match the pattern ‘csv’
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

# Combine all files in the list and export as CSV
df = pd.concat([pd.read_csv(f) for f in all_filenames ])
df.reset_index(drop=True, inplace=True)

# #export to csv
# df.to_csv( "spotify_data.csv", index=False, encoding='utf-8-sig')
# df.head(5)

In [5]:
df2 = df.drop(['track', 'artist', 'uri'], axis=1)
df2.head(2)

danceability  energy  key  loudness  mode  speechiness  acousticness  \
0         0.578   0.471    4    -7.270     1       0.0289        0.3680   
1         0.704   0.854   10    -5.477     0       0.1830        0.0185   

   instrumentalness  liveness  valence    tempo  duration_ms  time_signature  \
0               0.0     0.159    0.532  133.061       196707               4   
1               0.0     0.148    0.688   92.988       242587               4   

   chorus_hit  sections  target  
0    30.88059        13       1  
1    41.51106        10       1

In [6]:
#Validation of distribution of output values
df2.groupby("target").count()

danceability  energy    key  loudness   mode  speechiness  \
target                                                              
0              20553   20553  20553     20553  20553        20553   
1              20553   20553  20553     20553  20553        20553   

        acousticness  instrumentalness  liveness  valence  tempo  duration_ms  \
target                                                                          
0              20553             20553     20553    20553  20553        20553   
1              20553             20553     20553    20553  20553        20553   

        time_signature  chorus_hit  sections  
target                                        
0                20553       20553     20553  
1                20553       20553     20553

In [7]:
#Validation of correlation between variables
import numpy as np 
df3=df2.corr()
df3

danceability    energy       key  loudness      mode  \
danceability          1.000000  0.206128  0.015433  0.274160 -0.032743   
energy                0.206128  1.000000  0.022523  0.772628 -0.033780   
key                   0.015433  0.022523  1.000000  0.008438 -0.140455   
loudness              0.274160  0.772628  0.008438  1.000000  0.000509   
mode                 -0.032743 -0.033780 -0.140455  0.000509  1.000000   
speechiness           0.156452  0.122430  0.026515  0.069241 -0.059636   
acousticness         -0.261252 -0.715088 -0.024178 -0.566548  0.049961   
instrumentalness     -0.301915 -0.208153 -0.013101 -0.374301 -0.075992   
liveness             -0.115251  0.157779  0.000668  0.086708  0.008886   
valence               0.553858  0.341427  0.007742  0.271775  0.035636   
tempo                -0.066541  0.224018  0.001154  0.169453  0.027053   
duration_ms          -0.063030  0.011830  0.015493 -0.049890 -0.074828   
time_signature        0.191664  0.196072  0.004757  0.165520 -0.009483   
chorus_hit           -0.036277  0.009620  0.010264 -0.013401 -0.022594   
sections             -0.058615 -0.040233  0.006784 -0.080065 -0.057095   
target                0.346097  0.177142  0.009883  0.286034  0.079614   

                  speechiness  acousticness  instrumentalness  liveness  \
danceability         0.156452     -0.261252         -0.301915 -0.115251   
energy               0.122430     -0.715088         -0.208153  0.157779   
key                  0.026515     -0.024178         -0.013101  0.000668   
loudness             0.069241     -0.566548         -0.374301  0.086708   
mode                -0.059636      0.049961         -0.075992  0.008886   
speechiness          1.000000     -0.083948         -0.084092  0.131488   
acousticness        -0.083948      1.000000          0.204137 -0.030765   
instrumentalness    -0.084092      0.204137          1.000000 -0.050582   
liveness             0.131488     -0.030765         -0.050582  1.000000   
valence              0.001528     -0.195331         -0.287047  0.000784   
tempo                0.036854     -0.179700         -0.053618  0.024861   
duration_ms          0.007631     -0.070271          0.106551  0.005336   
time_signature       0.021085     -0.188139         -0.077980  0.004773   
chorus_hit           0.012972     -0.012409          0.048654  0.037981   
sections            -0.008636     -0.016824          0.081188 -0.011742   
target              -0.040835     -0.246036         -0.407638 -0.051445   

                   valence     tempo  duration_ms  time_signature  chorus_hit  \
danceability      0.553858 -0.066541    -0.063030        0.191664   -0.036277   
energy            0.341427  0.224018     0.011830        0.196072    0.009620   
key               0.007742  0.001154     0.015493        0.004757    0.010264   
loudness          0.271775  0.169453    -0.049890        0.165520   -0.013401   
mode              0.035636  0.027053    -0.074828       -0.009483   -0.022594   
speechiness       0.001528  0.036854     0.007631        0.021085    0.012972   
acousticness     -0.195331 -0.179700    -0.070271       -0.188139   -0.012409   
instrumentalness -0.287047 -0.053618     0.106551       -0.077980    0.048654   
liveness          0.000784  0.024861     0.005336        0.004773    0.037981   
valence           1.000000  0.107901    -0.172166        0.155669   -0.059120   
tempo             0.107901  1.000000    -0.024318        0.007659   -0.056054   
duration_ms      -0.172166 -0.024318     1.000000        0.018454    0.093875   
time_signature    0.155669  0.007659     0.018454        1.000000   -0.011281   
chorus_hit       -0.059120 -0.056054     0.093875       -0.011281    1.000000   
sections         -0.133527  0.024905     0.888952        0.008424   -0.085920   
target            0.251147  0.032649    -0.073820        0.104884   -0.046409   

                  sections    target  
danceability     -0.058615  0.346097  
energy           -0.040233 

In [8]:
# Sin chorus_hit
data = df2.values
X = df2[['danceability', 'energy', 'key', 'loudness','mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness','valence', 'tempo', 'duration_ms', 'time_signature', 'sections']]  
y = data[:, 15]
print(data.shape, X.shape, y.shape)
data

(41106, 16) (41106, 14) (41106,)


array([[ 0.578  ,  0.471  ,  4.     , ..., 30.88059, 13.     ,  1.     ],
       [ 0.704  ,  0.854  , 10.     , ..., 41.51106, 10.     ,  1.     ],
       [ 0.162  ,  0.836  ,  9.     , ..., 65.32887, 13.     ,  0.     ],
       ...,
       [ 0.562  ,  0.314  , 10.     , ..., 21.11763, 10.     ,  1.     ],
       [ 0.622  ,  0.781  ,  7.     , ..., 47.13558, 11.     ,  0.     ],
       [ 0.664  ,  0.739  ,  2.     , ..., 42.50341, 14.     ,  1.     ]])

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10)

## Data Preprocessing

In [10]:
#Scale features (X) using MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
X_scaler = MinMaxScaler(feature_range=(0,1)).fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test) 

X_train_scaled

array([[0.78947368, 0.52283395, 0.81818182, ..., 0.05569473, 0.8       ,
        0.06508876],
       [0.54048583, 0.83094117, 0.81818182, ..., 0.03957652, 0.8       ,
        0.04142012],
       [0.5       , 0.66588373, 0.81818182, ..., 0.03176775, 0.8       ,
        0.03550296],
       ...,
       [0.57692308, 0.36777999, 0.81818182, ..., 0.09203629, 0.8       ,
        0.09467456],
       [0.41902834, 0.16070793, 0.63636364, ..., 0.0441886 , 0.8       ,
        0.04733728],
       [0.29554656, 0.24873856, 0.81818182, ..., 0.0506431 , 0.6       ,
        0.06508876]])

One-hot encode the labels

In [11]:
#One-hot encode output labels (y)
from tensorflow.keras.utils import to_categorical
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

y_train_categorical

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

## Creating and defining our Deep Learning Model Architecture

In [12]:
#Create a sequential model
from tensorflow.keras.models import Sequential
model = Sequential() 

from tensorflow.keras.layers import Dense
number_inputs = 14  

#Create hidden layers
model.add(Dense(units=14,activation='relu', input_dim=number_inputs))
model.add(Dense(units=120,activation='relu'))
model.add(Dense(units=80,activation='relu'))
model.add(Dense(units=20,activation='relu'))

#Create output layer
number_classes = 2
model.add(Dense(units=number_classes, activation='softmax')) 

In [13]:
#Model Summary
model.summary() 

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 14)                210       
_________________________________________________________________
dense_1 (Dense)              (None, 120)               1800      
_________________________________________________________________
dense_2 (Dense)              (None, 80)                9680      
_________________________________________________________________
dense_3 (Dense)              (None, 20)                1620      
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 42        
Total params: 13,352
Trainable params: 13,352
Non-trainable params: 0
_________________________________________________________________


In [14]:
#Compile the Model
import tensorflow as tf

opt = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

## Training the Model

In [15]:
#Training the Model
import tensorflow as tf

history = model.fit(X_train_scaled, y_train_categorical, epochs=700, batch_size=1000, shuffle=True, verbose=2)

poch 362/700
31/31 - 0s - loss: 0.3988 - accuracy: 0.8116
Epoch 363/700
31/31 - 0s - loss: 0.3992 - accuracy: 0.8124
Epoch 364/700
31/31 - 0s - loss: 0.3991 - accuracy: 0.8144
Epoch 365/700
31/31 - 0s - loss: 0.3985 - accuracy: 0.8119
Epoch 366/700
31/31 - 0s - loss: 0.3987 - accuracy: 0.8123
Epoch 367/700
31/31 - 0s - loss: 0.3969 - accuracy: 0.8156
Epoch 368/700
31/31 - 0s - loss: 0.3998 - accuracy: 0.8129
Epoch 369/700
31/31 - 0s - loss: 0.3978 - accuracy: 0.8146
Epoch 370/700
31/31 - 0s - loss: 0.3976 - accuracy: 0.8129
Epoch 371/700
31/31 - 0s - loss: 0.3966 - accuracy: 0.8140
Epoch 372/700
31/31 - 0s - loss: 0.3956 - accuracy: 0.8167
Epoch 373/700
31/31 - 0s - loss: 0.3979 - accuracy: 0.8153
Epoch 374/700
31/31 - 0s - loss: 0.3965 - accuracy: 0.8163
Epoch 375/700
31/31 - 0s - loss: 0.3963 - accuracy: 0.8142
Epoch 376/700
31/31 - 0s - loss: 0.3969 - accuracy: 0.8138
Epoch 377/700
31/31 - 0s - loss: 0.4000 - accuracy: 0.8107
Epoch 378/700
31/31 - 0s - loss: 0.3994 - accuracy: 0.811

## Validation of the Model

In [16]:
#Evaluate the Model using the testing data
#Compare Model performace between training and testing data
model_loss_train, model_accuracy_train = model.evaluate(X_train_scaled, y_train_categorical, verbose=2)
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)

print(f"TRAINING DATA --> Loss: {model_loss_train}, Accuracy: {model_accuracy_train}")    
print(f"TESTING DATA --> Loss: {model_loss}, Accuracy: {model_accuracy}")

964/964 - 2s - loss: 0.3456 - accuracy: 0.8428
322/322 - 1s - loss: 0.6196 - accuracy: 0.7506
TRAINING DATA --> Loss: 0.3456403315067291, Accuracy: 0.8427779078483582
TESTING DATA --> Loss: 0.6195625066757202, Accuracy: 0.7506081461906433


## Saving the Trained Model

In [17]:
# # Save the model
# Define working directory
#os.chdir(r"C:\Users\hguzm\Documents\000. Personal\Bootcamp\Proyectos\FinalProject-Spotify")
#model.save("spotify_DeepLearning_Model.h5")

## Loading a Model

In [18]:
# Load the model  
# from tensorflow.keras.models import load_model
# # Define working directory
# os.chdir(r"C:\Users\hguzm\Documents\000. Personal\Bootcamp\Proyectos\FinalProject-Spotify")
# model = load_model("spotify_DeepLearning_Model.h5")

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 14)                210       
_________________________________________________________________
dense_1 (Dense)              (None, 120)               1800      
_________________________________________________________________
dense_2 (Dense)              (None, 80)                9680      
_________________________________________________________________
dense_3 (Dense)              (None, 20)                1620      
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 42        
Total params: 13,352
Trainable params: 13,352
Non-trainable params: 0
_________________________________________________________________


## Validation of the Model

In [20]:
#Evaluate the Model using the testing data
# model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)
    
# print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [21]:
# #Making Predictions with new data
# new_data = np.array([[0.2, 0.3, 0.4,0.2, 0.3, 0.4,0.2, 0.3, 0.4,0.2, 0.3, 0.4,0.2, 0.3, 0.4]])  # AQUI IRIA INFORMACIÓN DEL API
# print(f"Predicted class: {model.predict_classes(new_data)}")