In [1]:
import os
import glob
import pandas as pd


In [2]:
# Define working directory
os.chdir(r"C:\Users\hguzm\Documents\000. Personal\Bootcamp\Proyectos\FinalProject-Spotify\Original_data")

In [3]:
# Use glob to match the pattern ‘csv’
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

# Combine all files in the list and export as CSV
df = pd.concat([pd.read_csv(f) for f in all_filenames ])
df.reset_index(drop=True, inplace=True)

#export to csv
# df.to_csv( "spotify_data.csv", index=False, encoding='utf-8-sig')
# df.head(5)

In [4]:
df2 = df.drop(['track', 'artist', 'uri',"key", "tempo", "speechiness", "chorus_hit"], axis=1)
print(df2.count())
df2.head(2)

danceability        41106
energy              41106
loudness            41106
mode                41106
acousticness        41106
instrumentalness    41106
liveness            41106
valence             41106
duration_ms         41106
time_signature      41106
sections            41106
target              41106
dtype: int64


danceability  energy  loudness  mode  acousticness  instrumentalness  \
0         0.578   0.471    -7.270     1        0.3680               0.0   
1         0.704   0.854    -5.477     0        0.0185               0.0   

   liveness  valence  duration_ms  time_signature  sections  target  
0     0.159    0.532       196707               4        13       1  
1     0.148    0.688       242587               4        10       1

In [5]:
#Validation of distribution of output values
df2.groupby("target").count()

danceability  energy  loudness   mode  acousticness  instrumentalness  \
target                                                                          
0              20553   20553     20553  20553         20553             20553   
1              20553   20553     20553  20553         20553             20553   

        liveness  valence  duration_ms  time_signature  sections  
target                                                            
0          20553    20553        20553           20553     20553  
1          20553    20553        20553           20553     20553

In [6]:
#Validation of correlation between variables
import numpy as np 
df3=df2.corr()
df3

danceability    energy  loudness      mode  acousticness  \
danceability          1.000000  0.206128  0.274160 -0.032743     -0.261252   
energy                0.206128  1.000000  0.772628 -0.033780     -0.715088   
loudness              0.274160  0.772628  1.000000  0.000509     -0.566548   
mode                 -0.032743 -0.033780  0.000509  1.000000      0.049961   
acousticness         -0.261252 -0.715088 -0.566548  0.049961      1.000000   
instrumentalness     -0.301915 -0.208153 -0.374301 -0.075992      0.204137   
liveness             -0.115251  0.157779  0.086708  0.008886     -0.030765   
valence               0.553858  0.341427  0.271775  0.035636     -0.195331   
duration_ms          -0.063030  0.011830 -0.049890 -0.074828     -0.070271   
time_signature        0.191664  0.196072  0.165520 -0.009483     -0.188139   
sections             -0.058615 -0.040233 -0.080065 -0.057095     -0.016824   
target                0.346097  0.177142  0.286034  0.079614     -0.246036   

                  instrumentalness  liveness   valence  duration_ms  \
danceability             -0.301915 -0.115251  0.553858    -0.063030   
energy                   -0.208153  0.157779  0.341427     0.011830   
loudness                 -0.374301  0.086708  0.271775    -0.049890   
mode                     -0.075992  0.008886  0.035636    -0.074828   
acousticness              0.204137 -0.030765 -0.195331    -0.070271   
instrumentalness          1.000000 -0.050582 -0.287047     0.106551   
liveness                 -0.050582  1.000000  0.000784     0.005336   
valence                  -0.287047  0.000784  1.000000    -0.172166   
duration_ms               0.106551  0.005336 -0.172166     1.000000   
time_signature           -0.077980  0.004773  0.155669     0.018454   
sections                  0.081188 -0.011742 -0.133527     0.888952   
target                   -0.407638 -0.051445  0.251147    -0.073820   

                  time_signature  sections    target  
danceability            0.191664 -0.058615  0.346097  
energy                  0.196072 -0.040233  0.177142  
loudness                0.165520 -0.080065  0.286034  
mode                   -0.009483 -0.057095  0.079614  
acousticness           -0.188139 -0.016824 -0.246036  
instrumentalness       -0.077980  0.081188 -0.407638  
liveness                0.004773 -0.011742 -0.051445  
valence                 0.155669 -0.133527  0.251147  
duration_ms             0.018454  0.888952 -0.073820  
time_signature          1.000000  0.008424  0.104884  
sections                0.008424  1.000000 -0.059997  
target                  0.104884 -0.059997  1.000000

In [7]:
# Reformat data
data = df2.values
X = data[:, 0:11]  
y = data[:, 11]

print(data.shape, X.shape, y.shape)
data
# X[0]
# y

(41106, 12) (41106, 11) (41106,)


array([[  0.578,   0.471,  -7.27 , ...,   4.   ,  13.   ,   1.   ],
       [  0.704,   0.854,  -5.477, ...,   4.   ,  10.   ,   1.   ],
       [  0.162,   0.836,  -3.009, ...,   4.   ,  13.   ,   0.   ],
       ...,
       [  0.562,   0.314, -15.213, ...,   4.   ,  10.   ,   1.   ],
       [  0.622,   0.781,  -6.08 , ...,   4.   ,  11.   ,   0.   ],
       [  0.664,   0.739,  -9.005, ...,   4.   ,  14.   ,   1.   ]])

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10)

## Data Preprocessing

In [9]:
#Scale features (X) using MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
X_scaler = MinMaxScaler(feature_range=(0,1)).fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test) 

X_train_scaled

array([[0.78947368, 0.52283395, 0.76172236, ..., 0.05569473, 0.8       ,
        0.06508876],
       [0.54048583, 0.83094117, 0.77921392, ..., 0.03957652, 0.8       ,
        0.04142012],
       [0.5       , 0.66588373, 0.7455139 , ..., 0.03176775, 0.8       ,
        0.03550296],
       ...,
       [0.57692308, 0.36777999, 0.68303866, ..., 0.09203629, 0.8       ,
        0.09467456],
       [0.41902834, 0.16070793, 0.50819858, ..., 0.0441886 , 0.8       ,
        0.04733728],
       [0.29554656, 0.24873856, 0.67937808, ..., 0.0506431 , 0.6       ,
        0.06508876]])

One-hot encode the labels

In [10]:
#One-hot encode output labels (y)
from tensorflow.keras.utils import to_categorical
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

y_train_categorical

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

## Creating and defining our Deep Learning Model Architecture

In [11]:
#Create a sequential model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential() 


number_inputs = 11  

#Create hidden layers
model.add(Dense(units=14,activation='relu', input_dim=number_inputs))
model.add(Dense(units=120,activation='relu'))
model.add(Dense(units=80,activation='relu'))

#Create output layer
number_classes = 2
model.add(Dense(units=number_classes, activation='softmax')) 

Number of Hidden Nodes 
https://stats.stackexchange.com/questions/181/how-to-choose-the-number-of-hidden-layers-and-nodes-in-a-feedforward-neural-netw#:~:text=The%20number%20of%20hidden%20neurons,size%20of%20the%20input%20layer.

In [12]:
#Model Summary
model.summary() 

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 14)                168       
_________________________________________________________________
dense_1 (Dense)              (None, 120)               1800      
_________________________________________________________________
dense_2 (Dense)              (None, 80)                9680      
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 162       
Total params: 11,810
Trainable params: 11,810
Non-trainable params: 0
_________________________________________________________________


In [13]:
#Compile the Model
import tensorflow as tf

opt = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

## Training the Model

In [14]:
#Training the Model
import tensorflow as tf

history = model.fit(X_train_scaled, y_train_categorical, epochs=500, batch_size=2000, shuffle=True, verbose=2)

poch 162/500
16/16 - 0s - loss: 0.4747 - accuracy: 0.7677
Epoch 163/500
16/16 - 0s - loss: 0.4752 - accuracy: 0.7663
Epoch 164/500
16/16 - 0s - loss: 0.4758 - accuracy: 0.7667
Epoch 165/500
16/16 - 0s - loss: 0.4770 - accuracy: 0.7648
Epoch 166/500
16/16 - 0s - loss: 0.4740 - accuracy: 0.7675
Epoch 167/500
16/16 - 0s - loss: 0.4741 - accuracy: 0.7689
Epoch 168/500
16/16 - 0s - loss: 0.4741 - accuracy: 0.7684
Epoch 169/500
16/16 - 0s - loss: 0.4738 - accuracy: 0.7683
Epoch 170/500
16/16 - 0s - loss: 0.4740 - accuracy: 0.7685
Epoch 171/500
16/16 - 0s - loss: 0.4749 - accuracy: 0.7684
Epoch 172/500
16/16 - 0s - loss: 0.4745 - accuracy: 0.7684
Epoch 173/500
16/16 - 0s - loss: 0.4739 - accuracy: 0.7674
Epoch 174/500
16/16 - 0s - loss: 0.4730 - accuracy: 0.7689
Epoch 175/500
16/16 - 0s - loss: 0.4729 - accuracy: 0.7686
Epoch 176/500
16/16 - 0s - loss: 0.4744 - accuracy: 0.7689
Epoch 177/500
16/16 - 0s - loss: 0.4739 - accuracy: 0.7685
Epoch 178/500
16/16 - 0s - loss: 0.4729 - accuracy: 0.769

## Validation of the Model

In [15]:
#Evaluate the Model using the testing data
#Compare Model performace between training and testing data
model_loss_train, model_accuracy_train = model.evaluate(X_train_scaled, y_train_categorical, verbose=2)
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)

print(f"TRAINING DATA --> Loss: {model_loss_train}, Accuracy: {model_accuracy_train}")    
print(f"TESTING DATA --> Loss: {model_loss}, Accuracy: {model_accuracy}")

964/964 - 3s - loss: 0.4447 - accuracy: 0.7864
322/322 - 1s - loss: 0.4831 - accuracy: 0.7721
TRAINING DATA --> Loss: 0.4447202682495117, Accuracy: 0.7864024043083191
TESTING DATA --> Loss: 0.48307517170906067, Accuracy: 0.7721124887466431


## Saving the Trained Model

In [16]:
# # Save the model
# Define working directory
os.chdir(r"C:\Users\hguzm\Documents\000. Personal\Bootcamp\Proyectos\FinalProject-Spotify")
# model.save("spotify_DeepLearning_Model.h5")

## Loading a Model

In [17]:
# Load the model  
from tensorflow.keras.models import load_model
# Define working directory
os.chdir(r"C:\Users\hguzm\Documents\000. Personal\Bootcamp\Proyectos\FinalProject-Spotify")
# model = load_model("spotify_DeepLearning_Model.h5")

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 14)                168       
_________________________________________________________________
dense_1 (Dense)              (None, 120)               1800      
_________________________________________________________________
dense_2 (Dense)              (None, 80)                9680      
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 162       
Total params: 11,810
Trainable params: 11,810
Non-trainable params: 0
_________________________________________________________________


## Validation of the Model

In [19]:
# #Evaluate the Model using the testing data
# model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)
    
# print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [20]:
# #Making Predictions with new data
# new_data = np.array([[0.2, 0.3, 0.4,0.2, 0.3, 0.4,0.2, 0.3, 0.4,0.2, 0.3, 0.4,0.2, 0.3, 0.4]])  # AQUI IRIA INFORMACIÓN DEL API
# print(f"Predicted class: {model.predict_classes(new_data)}")