In [2]:
from google.colab import files
uploaded = files.upload()

Saving dataset-of-00s.csv to dataset-of-00s.csv
Saving dataset-of-10s.csv to dataset-of-10s.csv
Saving dataset-of-60s.csv to dataset-of-60s.csv
Saving dataset-of-70s.csv to dataset-of-70s.csv
Saving dataset-of-80s.csv to dataset-of-80s.csv
Saving dataset-of-90s.csv to dataset-of-90s.csv


In [3]:
import os
import glob
import pandas as pd

In [4]:
# Define working directory
# os.chdir(r"C:\Users\hguzm\Documents\000. Personal\Bootcamp\Proyectos\FinalProject-Spotify\Original_data")

In [5]:
# Use glob to match the pattern ‘csv’
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

# Combine all files in the list and export as CSV
df = pd.concat([pd.read_csv(f) for f in all_filenames ])
df.reset_index(drop=True, inplace=True)

#export to csv
df.to_csv( "spotify_data.csv", index=False, encoding='utf-8-sig')
df.head(5)

track             artist  ... sections  target
0                 Lucky Man  Montgomery Gentry  ...       13       1
1            On The Hotline       Pretty Ricky  ...       10       1
2        Clouds Of Dementia         Candlemass  ...       13       0
3  Heavy Metal, Raise Hell!      Zwartketterij  ...        9       0
4           I Got A Feelin'   Billy Currington  ...       10       1

[5 rows x 19 columns]

In [6]:
df2 = df.drop(['track', 'artist', 'uri'], axis=1)
df2.head(2)

danceability  energy  key  ...  chorus_hit  sections  target
0         0.578   0.471    4  ...    30.88059        13       1
1         0.704   0.854   10  ...    41.51106        10       1

[2 rows x 16 columns]

In [7]:
#Validation of distribution of output values
df2.groupby("target").count()

danceability  energy    key  ...  time_signature  chorus_hit  sections
target                               ...                                      
0              20553   20553  20553  ...           20553       20553     20553
1              20553   20553  20553  ...           20553       20553     20553

[2 rows x 15 columns]

In [8]:
#Validation of correlation between variables
import numpy as np 
df3=df2.corr()
df3

danceability    energy  ...  sections    target
danceability          1.000000  0.206128  ... -0.058615  0.346097
energy                0.206128  1.000000  ... -0.040233  0.177142
key                   0.015433  0.022523  ...  0.006784  0.009883
loudness              0.274160  0.772628  ... -0.080065  0.286034
mode                 -0.032743 -0.033780  ... -0.057095  0.079614
speechiness           0.156452  0.122430  ... -0.008636 -0.040835
acousticness         -0.261252 -0.715088  ... -0.016824 -0.246036
instrumentalness     -0.301915 -0.208153  ...  0.081188 -0.407638
liveness             -0.115251  0.157779  ... -0.011742 -0.051445
valence               0.553858  0.341427  ... -0.133527  0.251147
tempo                -0.066541  0.224018  ...  0.024905  0.032649
duration_ms          -0.063030  0.011830  ...  0.888952 -0.073820
time_signature        0.191664  0.196072  ...  0.008424  0.104884
chorus_hit           -0.036277  0.009620  ... -0.085920 -0.046409
sections             -0.058615 -0.040233  ...  1.000000 -0.059997
target                0.346097  0.177142  ... -0.059997  1.000000

[16 rows x 16 columns]

In [9]:
#1. Sin key - crih
#2. Sin Tempo - chris  / - purvi
#3. Sin speechiness / purvi  -grecia
#4. Sin chorus_hit  / grecia 
#5. Sin key, Tempo, speechiness, chorus_hit- heidy


In [10]:
# Sin chorus_hit y speechiness
data = df2.values
X = df2[['danceability', 'energy', 'key', 'loudness','mode', 'acousticness', 'instrumentalness', 'liveness','valence', 'tempo', 'duration_ms', 'time_signature', 'sections']]  
y = data[:, 15]

In [11]:
# Reformat data
# data = df2.values
# X = data[:, 0:15]  
# y = data[:, 15]

print(data.shape, X.shape, y.shape)
data
# X[0]
# y

(41106, 16) (41106, 13) (41106,)


array([[ 0.578  ,  0.471  ,  4.     , ..., 30.88059, 13.     ,  1.     ],
       [ 0.704  ,  0.854  , 10.     , ..., 41.51106, 10.     ,  1.     ],
       [ 0.162  ,  0.836  ,  9.     , ..., 65.32887, 13.     ,  0.     ],
       ...,
       [ 0.719  ,  0.804  , 10.     , ..., 20.73371,  7.     ,  1.     ],
       [ 0.6    ,  0.177  ,  7.     , ..., 21.65301, 14.     ,  0.     ],
       [ 0.121  ,  0.123  ,  4.     , ..., 71.05343, 15.     ,  0.     ]])

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10)

## Data Preprocessing

In [13]:
#Scale features (X) using MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
X_scaler = MinMaxScaler(feature_range=(0,1)).fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test) 

X_train_scaled

array([[0.45544554, 0.80695154, 0.        , ..., 0.05761146, 0.8       ,
        0.0591716 ],
       [0.68790357, 0.44386041, 0.90909091, ..., 0.11360416, 1.        ,
        0.09467456],
       [0.42100732, 0.43085715, 0.18181818, ..., 0.04610404, 0.8       ,
        0.05325444],
       ...,
       [0.62871287, 0.8159538 , 0.63636364, ..., 0.06279068, 0.8       ,
        0.08284024],
       [0.73956091, 0.49687372, 0.09090909, ..., 0.03433116, 0.8       ,
        0.04733728],
       [0.46190271, 0.30582576, 0.36363636, ..., 0.05566347, 0.8       ,
        0.07692308]])

One-hot encode the labels

In [14]:
#One-hot encode output labels (y)
from tensorflow.keras.utils import to_categorical
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

y_train_categorical

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

## Creating and defining our Deep Learning Model Architecture

In [18]:
#Create a sequential model
from tensorflow.keras.models import Sequential
model = Sequential() 

from tensorflow.keras.layers import Dense
number_inputs = 13  

#Create hidden layers
model.add(Dense(units=13,activation='relu', input_dim=number_inputs))
model.add(Dense(units=120,activation='relu'))
model.add(Dense(units=80,activation='relu'))

#Create output layer
number_classes = 2
model.add(Dense(units=number_classes, activation='softmax')) 

Number of Hidden Nodes 
https://stats.stackexchange.com/questions/181/how-to-choose-the-number-of-hidden-layers-and-nodes-in-a-feedforward-neural-netw#:~:text=The%20number%20of%20hidden%20neurons,size%20of%20the%20input%20layer.

In [19]:
#Model Summary
model.summary() 

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 13)                182       
_________________________________________________________________
dense_5 (Dense)              (None, 120)               1680      
_________________________________________________________________
dense_6 (Dense)              (None, 80)                9680      
_________________________________________________________________
dense_7 (Dense)              (None, 2)                 162       
Total params: 11,704
Trainable params: 11,704
Non-trainable params: 0
_________________________________________________________________


In [20]:
#Compile the Model
model.compile(optimizer='nadam', loss='categorical_crossentropy', metrics=['accuracy'])

## Training the Model

In [21]:
#Training the Model
import tensorflow as tf

model.fit(X_train_scaled,y_train_categorical,epochs=500, batch_size=2000, shuffle=True, verbose=2)

Epoch 1/500
16/16 - 0s - loss: 0.6727 - accuracy: 0.6021
Epoch 2/500
16/16 - 0s - loss: 0.5987 - accuracy: 0.6947
Epoch 3/500
16/16 - 0s - loss: 0.5505 - accuracy: 0.7136
Epoch 4/500
16/16 - 0s - loss: 0.5387 - accuracy: 0.7187
Epoch 5/500
16/16 - 0s - loss: 0.5311 - accuracy: 0.7252
Epoch 6/500
16/16 - 0s - loss: 0.5268 - accuracy: 0.7291
Epoch 7/500
16/16 - 0s - loss: 0.5234 - accuracy: 0.7317
Epoch 8/500
16/16 - 0s - loss: 0.5198 - accuracy: 0.7357
Epoch 9/500
16/16 - 0s - loss: 0.5181 - accuracy: 0.7373
Epoch 10/500
16/16 - 0s - loss: 0.5161 - accuracy: 0.7391
Epoch 11/500
16/16 - 0s - loss: 0.5171 - accuracy: 0.7365
Epoch 12/500
16/16 - 0s - loss: 0.5116 - accuracy: 0.7411
Epoch 13/500
16/16 - 0s - loss: 0.5097 - accuracy: 0.7433
Epoch 14/500
16/16 - 0s - loss: 0.5093 - accuracy: 0.7427
Epoch 15/500
16/16 - 0s - loss: 0.5077 - accuracy: 0.7442
Epoch 16/500
16/16 - 0s - loss: 0.5080 - accuracy: 0.7437
Epoch 17/500
16/16 - 0s - loss: 0.5066 - accuracy: 0.7446
Epoch 18/500
16/16 - 0s

## Validation of the Model

In [22]:
#Evaluate the Model using the testing data
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)
    
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

322/322 - 0s - loss: 0.4830 - accuracy: 0.7692
Loss: 0.4829934537410736, Accuracy: 0.7691933512687683


## Saving the Trained Model

In [ ]:
# # Save the model
# Define working directory
#os.chdir(r"C:\Users\hguzm\Documents\000. Personal\Bootcamp\Proyectos\FinalProject-Spotify")
#model.save("spotify_DeepLearning_Model.h5")

## Loading a Model

In [ ]:
# Load the model  
from tensorflow.keras.models import load_model
# Define working directory
os.chdir(r"C:\Users\hguzm\Documents\000. Personal\Bootcamp\Proyectos\FinalProject-Spotify")
model = load_model("spotify_DeepLearning_Model.h5")

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 15)                240       
_________________________________________________________________
dense_1 (Dense)              (None, 120)               1920      
_________________________________________________________________
dense_2 (Dense)              (None, 80)                9680      
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 162       
Total params: 12,002
Trainable params: 12,002
Non-trainable params: 0
_________________________________________________________________


## Validation of the Model

In [ ]:
#Evaluate the Model using the testing data
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)
    
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

322/322 - 0s - loss: 0.4824 - accuracy: 0.7732
Loss: 0.48241570591926575, Accuracy: 0.7731828093528748


In [ ]:
# #Making Predictions with new data
# new_data = np.array([[0.2, 0.3, 0.4,0.2, 0.3, 0.4,0.2, 0.3, 0.4,0.2, 0.3, 0.4,0.2, 0.3, 0.4]])  # AQUI IRIA INFORMACIÓN DEL API
# print(f"Predicted class: {model.predict_classes(new_data)}")