In [1]:
import os
import glob
import pandas as pd

In [2]:
# Define working directory
os.chdir(r"C:\Users\Cristina Bardan\Desktop\Repositories\FinalProject-Spotify\Original_data")

In [3]:
# Use glob to match the pattern ‘csv’
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

# Combine all files in the list and export as CSV
df = pd.concat([pd.read_csv(f) for f in all_filenames ])
df.reset_index(drop=True, inplace=True)

In [4]:
df2 = df.drop(['track', 'artist', 'uri'], axis=1)

In [5]:
#Validation of correlation between variables
import numpy as np 
df3=df2.corr()

In [6]:
# Sin chorus_hit y speechiness
data = df2.values
X = df2[['danceability', 'energy', 'key', 'loudness','mode', 'acousticness', 'instrumentalness', 'liveness','valence', 'tempo', 'duration_ms', 'time_signature', 'sections']]  
y = data[:, 15]
print(data.shape, X.shape, y.shape)
data

(41106, 16) (41106, 13) (41106,)


array([[ 0.578  ,  0.471  ,  4.     , ..., 30.88059, 13.     ,  1.     ],
       [ 0.704  ,  0.854  , 10.     , ..., 41.51106, 10.     ,  1.     ],
       [ 0.162  ,  0.836  ,  9.     , ..., 65.32887, 13.     ,  0.     ],
       ...,
       [ 0.562  ,  0.314  , 10.     , ..., 21.11763, 10.     ,  1.     ],
       [ 0.622  ,  0.781  ,  7.     , ..., 47.13558, 11.     ,  0.     ],
       [ 0.664  ,  0.739  ,  2.     , ..., 42.50341, 14.     ,  1.     ]])

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10)

## Data Preprocessing

In [8]:
#Scale features (X) using MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
X_scaler = MinMaxScaler(feature_range=(0,1)).fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test) 

X_train_scaled

array([[0.78947368, 0.52283395, 0.81818182, ..., 0.05569473, 0.8       ,
        0.06508876],
       [0.54048583, 0.83094117, 0.81818182, ..., 0.03957652, 0.8       ,
        0.04142012],
       [0.5       , 0.66588373, 0.81818182, ..., 0.03176775, 0.8       ,
        0.03550296],
       ...,
       [0.57692308, 0.36777999, 0.81818182, ..., 0.09203629, 0.8       ,
        0.09467456],
       [0.41902834, 0.16070793, 0.63636364, ..., 0.0441886 , 0.8       ,
        0.04733728],
       [0.29554656, 0.24873856, 0.81818182, ..., 0.0506431 , 0.6       ,
        0.06508876]])

One-hot encode the labels

In [9]:
#One-hot encode output labels (y)
from tensorflow.keras.utils import to_categorical
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

y_train_categorical

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

## Creating and defining our Deep Learning Model Architecture

In [10]:
#Create a sequential model
from tensorflow.keras.models import Sequential
model = Sequential() 

from tensorflow.keras.layers import Dense
number_inputs = 13  

#Create hidden layers
model.add(Dense(units=14,activation='relu', input_dim=number_inputs))
model.add(Dense(units=120,activation='relu'))
model.add(Dense(units=80,activation='relu'))


#Create output layer
number_classes = 2
model.add(Dense(units=number_classes, activation='softmax')) 

Number of Hidden Nodes 
https://stats.stackexchange.com/questions/181/how-to-choose-the-number-of-hidden-layers-and-nodes-in-a-feedforward-neural-netw#:~:text=The%20number%20of%20hidden%20neurons,size%20of%20the%20input%20layer.

In [11]:
#Model Summary
model.summary() 

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 14)                196       
_________________________________________________________________
dense_1 (Dense)              (None, 120)               1800      
_________________________________________________________________
dense_2 (Dense)              (None, 80)                9680      
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 162       
Total params: 11,838
Trainable params: 11,838
Non-trainable params: 0
_________________________________________________________________


In [12]:
#Compile the Model
import tensorflow as tf

opt = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

## Training the Model

In [13]:
#Training the Model
history = model.fit(X_train_scaled, y_train_categorical, epochs=500, batch_size=2000, shuffle=True, verbose=2)

Epoch 1/500
16/16 - 0s - loss: 0.6684 - accuracy: 0.6340
Epoch 2/500
16/16 - 0s - loss: 0.6125 - accuracy: 0.6950
Epoch 3/500
16/16 - 0s - loss: 0.5569 - accuracy: 0.7097
Epoch 4/500
16/16 - 0s - loss: 0.5406 - accuracy: 0.7213
Epoch 5/500
16/16 - 0s - loss: 0.5337 - accuracy: 0.7294
Epoch 6/500
16/16 - 0s - loss: 0.5290 - accuracy: 0.7328
Epoch 7/500
16/16 - 0s - loss: 0.5257 - accuracy: 0.7357
Epoch 8/500
16/16 - 0s - loss: 0.5228 - accuracy: 0.7389
Epoch 9/500
16/16 - 0s - loss: 0.5202 - accuracy: 0.7407
Epoch 10/500
16/16 - 0s - loss: 0.5178 - accuracy: 0.7393
Epoch 11/500
16/16 - 0s - loss: 0.5159 - accuracy: 0.7414
Epoch 12/500
16/16 - 0s - loss: 0.5134 - accuracy: 0.7437
Epoch 13/500
16/16 - 0s - loss: 0.5111 - accuracy: 0.7445
Epoch 14/500
16/16 - 0s - loss: 0.5100 - accuracy: 0.7449
Epoch 15/500
16/16 - 0s - loss: 0.5095 - accuracy: 0.7464
Epoch 16/500
16/16 - 0s - loss: 0.5080 - accuracy: 0.7471
Epoch 17/500
16/16 - 0s - loss: 0.5071 - accuracy: 0.7489
Epoch 18/500
16/16 - 0s

## Validation of the Model

In [14]:
#Evaluate the Model using the testing data
#Compare Model performace between training and testing data
model_loss_train, model_accuracy_train = model.evaluate(X_train_scaled, y_train_categorical, verbose=2)
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)

print(f"TRAINING DATA --> Loss: {model_loss_train}, Accuracy: {model_accuracy_train}")    
print(f"TESTING DATA --> Loss: {model_loss}, Accuracy: {model_accuracy}")

964/964 - 1s - loss: 0.4454 - accuracy: 0.7881
322/322 - 0s - loss: 0.4818 - accuracy: 0.7699
TRAINING DATA --> Loss: 0.4454091191291809, Accuracy: 0.7880891561508179
TESTING DATA --> Loss: 0.48179200291633606, Accuracy: 0.7698744535446167


## Saving the Trained Model

In [15]:
# Save the model
model.save("../Models/h5/schorus&speech.h5")